# Generated by Django 5.2.17 on 2026-09-05 23:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='kod')),
                ('name', models.CharField(max_length=120, verbose_name='nazwa')),
                ('is_online', models.BooleanField(default=False, verbose_name='obsługuje sklep online')),
                ('active', models.BooleanField(default=True, verbose_name='aktywna')),
            ],
            options={
                'verbose_name': 'lokalizacja magazynowa',
                'verbose_name_plural': 'lokalizacje magazynowe',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nazwa')),
                ('gross_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='cena brutto')),
                ('active', models.BooleanField(default=True, verbose_name='aktywny')),
            ],
            options={
                'verbose_name': 'próg cenowy',
                'verbose_name_plural': 'progi cenowe',
                'ordering': ('gross_price', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_key', models.SlugField(max_length=100, unique=True, verbose_name='klucz produktu')),
                ('working_name', models.CharField(max_length=180, verbose_name='nazwa robocza')),
                ('display_name', models.CharField(blank=True, max_length=180, verbose_name='nazwa w sklepie')),
                ('slug', models.SlugField(max_length=190, unique=True, verbose_name='adres produktu')),
                ('category', models.CharField(choices=[('SOCKS', 'Skarpety'), ('FOOTIES', 'Stopki'), ('TIGHTS', 'Rajstopy'), ('OTHER', 'Inne')], max_length=20, verbose_name='kategoria')),
                ('source_type', models.CharField(choices=[('RELAX', 'Produkcja Relax'), ('EXTERNAL', 'Inny producent')], max_length=20, verbose_name='pochodzenie')),
                ('manufacturer', models.CharField(blank=True, max_length=160, verbose_name='producent')),
                ('audience', models.CharField(choices=[('CHILDREN', 'Dzieci'), ('ADULTS', 'Dorośli'), ('UNIVERSAL', 'Uniwersalne')], default='UNIVERSAL', max_length=20, verbose_name='grupa')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('materials', models.CharField(blank=True, max_length=300, verbose_name='materiały')),
                ('status', models.CharField(choices=[('DRAFT', 'Szkic'), ('ACTIVE', 'Aktywny'), ('ARCHIVED', 'Archiwalny')], default='DRAFT', max_length=20, verbose_name='status')),
                ('published', models.BooleanField(default=False, verbose_name='opublikowany')),
            ],
            options={
                'verbose_name': 'produkt',
                'verbose_name_plural': 'produkty',
                'ordering': ('working_name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nazwa')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='identyfikator')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tagi',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_hand', models.PositiveIntegerField(default=0, verbose_name='na stanie')),
                ('reserved', models.PositiveIntegerField(default=0, verbose_name='zarezerwowane')),
                ('low_stock_threshold', models.PositiveIntegerField(default=3, verbose_name='alarm od')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='catalog.inventorylocation', verbose_name='lokalizacja')),
            ],
            options={
                'verbose_name': 'stan magazynowy',
                'verbose_name_plural': 'stany magazynowe',
            },
        ),
        migrations.CreateModel(
            name='PromotionSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rationale', models.TextField(verbose_name='uzasadnienie')),
                ('suggested_price_gross', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='sugerowana cena brutto')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='od')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='do')),
                ('status', models.CharField(choices=[('PENDING', 'Oczekuje'), ('APPROVED', 'Zatwierdzona'), ('REJECTED', 'Odrzucona')], default='PENDING', max_length=20, verbose_name='status')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='data decyzji')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='decyzja użytkownika')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_suggestions', to='catalog.product', verbose_name='produkt')),
            ],
            options={
                'verbose_name': 'propozycja promocji',
                'verbose_name_plural': 'propozycje promocji',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('RECEIPT', 'Przyjęcie'), ('CORRECTION', 'Korekta'), ('SALE', 'Sprzedaż'), ('RETURN', 'Zwrot'), ('TRANSFER', 'Przeniesienie')], max_length=20, verbose_name='rodzaj')),
                ('quantity', models.IntegerField(verbose_name='zmiana')),
                ('balance_after', models.PositiveIntegerField(verbose_name='stan po zmianie')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='uwagi')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.inventorybalance', verbose_name='stan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'ruch magazynowy',
                'verbose_name_plural': 'ruchy magazynowe',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.tag', verbose_name='tagi'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='kod kreskowy')),
                ('size_label', models.CharField(max_length=80, verbose_name='rozmiar')),
                ('color_name', models.CharField(max_length=100, verbose_name='kolor')),
                ('pattern_name', models.CharField(blank=True, max_length=120, verbose_name='wzór')),
                ('price_override_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='własna cena brutto')),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='VAT (%)')),
                ('active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('price_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.pricetier', verbose_name='próg cenowy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='produkt')),
            ],
            options={
                'verbose_name': 'wariant',
                'verbose_name_plural': 'warianty',
                'ordering': ('product__working_name', 'size_label', 'color_name'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/%Y/%m', verbose_name='zdjęcie')),
                ('alt_text', models.CharField(blank=True, max_length=220, verbose_name='opis alternatywny')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='kolejność')),
                ('primary', models.BooleanField(default=False, verbose_name='główne')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='produkt')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.variant', verbose_name='wariant')),
            ],
            options={
                'verbose_name': 'zdjęcie produktu',
                'verbose_name_plural': 'zdjęcia produktów',
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='catalog.variant', verbose_name='wariant'),
        ),
        migrations.CreateModel(
            name='ProductMetricDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='dzień')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='odsłony')),
                ('cart_additions', models.PositiveIntegerField(default=0, verbose_name='dodania do koszyka')),
                ('paid_quantity', models.PositiveIntegerField(default=0, verbose_name='opłacone sztuki')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='catalog.product', verbose_name='produkt')),
            ],
            options={
                'verbose_name': 'dzienna statystyka produktu',
                'verbose_name_plural': 'dzienne statystyki produktów',
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('product', 'date'), name='unique_product_metric_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('product', 'size_label', 'color_name', 'pattern_name'), name='unique_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('variant', 'location'), name='unique_variant_location'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='reserved_not_above_stock'),
        ),
    ]
