# Generated by Django 5.2.17 on 2026-09-05 23:31

import django.core.validators
import django.db.models.deletion
import orders.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(default=orders.models.new_order_number, editable=False, max_length=30, unique=True, verbose_name='numer')),
                ('status', models.CharField(choices=[('AWAITING_PAYMENT', 'Oczekuje na płatność'), ('PAID', 'Opłacone'), ('PREPARING', 'W przygotowaniu'), ('SHIPPED', 'Wysłane'), ('COMPLETED', 'Zakończone'), ('CANCELLED', 'Anulowane'), ('REFUNDED', 'Zwrócone')], default='AWAITING_PAYMENT', max_length=24, verbose_name='status')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('first_name', models.CharField(max_length=100, verbose_name='imię')),
                ('last_name', models.CharField(max_length=120, verbose_name='nazwisko')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefon')),
                ('shipping_method_code', models.CharField(blank=True, max_length=80, verbose_name='kod dostawy')),
                ('shipping_method_name', models.CharField(blank=True, max_length=160, verbose_name='sposób dostawy')),
                ('address_line_1', models.CharField(blank=True, max_length=180, verbose_name='adres')),
                ('address_line_2', models.CharField(blank=True, max_length=180, verbose_name='adres — ciąg dalszy')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='kod pocztowy')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='miejscowość')),
                ('country_code', models.CharField(default='PL', max_length=2, verbose_name='kraj')),
                ('pickup_point', models.CharField(blank=True, max_length=160, verbose_name='punkt odbioru')),
                ('invoice_requested', models.BooleanField(default=False, verbose_name='faktura')),
                ('company_name', models.CharField(blank=True, max_length=180, verbose_name='firma')),
                ('tax_id', models.CharField(blank=True, max_length=30, verbose_name='NIP')),
                ('customer_note', models.TextField(blank=True, verbose_name='uwagi klienta')),
                ('items_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='produkty brutto')),
                ('shipping_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='dostawa brutto')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='razem brutto')),
                ('currency', models.CharField(default='PLN', max_length=3, verbose_name='waluta')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='opłacono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'zamówienie',
                'verbose_name_plural': 'zamówienia',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=180, verbose_name='produkt')),
                ('sku', models.CharField(blank=True, max_length=80, verbose_name='SKU')),
                ('size_label', models.CharField(max_length=80, verbose_name='rozmiar')),
                ('color_name', models.CharField(max_length=100, verbose_name='kolor')),
                ('pattern_name', models.CharField(blank=True, max_length=120, verbose_name='wzór')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='liczba')),
                ('unit_gross', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cena jednostkowa brutto')),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='wartość brutto')),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VAT (%)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='zamówienie')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.variant', verbose_name='wariant')),
            ],
            options={
                'verbose_name': 'pozycja zamówienia',
                'verbose_name_plural': 'pozycje zamówienia',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=24, verbose_name='poprzedni status')),
                ('to_status', models.CharField(choices=[('AWAITING_PAYMENT', 'Oczekuje na płatność'), ('PAID', 'Opłacone'), ('PREPARING', 'W przygotowaniu'), ('SHIPPED', 'Wysłane'), ('COMPLETED', 'Zakończone'), ('CANCELLED', 'Anulowane'), ('REFUNDED', 'Zwrócone')], max_length=24, verbose_name='nowy status')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='zamówienie')),
            ],
            options={
                'verbose_name': 'zmiana statusu',
                'verbose_name_plural': 'historia statusów',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, max_length=80, verbose_name='operator')),
                ('method', models.CharField(blank=True, max_length=80, verbose_name='metoda')),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=180, verbose_name='identyfikator operatora')),
                ('last_event_id', models.CharField(blank=True, max_length=180, verbose_name='ostatnie zdarzenie')),
                ('status', models.CharField(choices=[('CREATED', 'Utworzona'), ('PENDING', 'Oczekuje'), ('PAID', 'Opłacona'), ('FAILED', 'Nieudana'), ('REFUNDED', 'Zwrócona')], default='CREATED', max_length=20, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='kwota')),
                ('currency', models.CharField(default='PLN', max_length=3, verbose_name='waluta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='zamówienie')),
            ],
            options={
                'verbose_name': 'płatność',
                'verbose_name_plural': 'płatności',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='liczba')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktywna'), ('CONSUMED', 'Zrealizowana'), ('RELEASED', 'Zwolniona')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='wygasa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.inventorybalance', verbose_name='stan')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='orders.orderline', verbose_name='pozycja')),
            ],
            options={
                'verbose_name': 'rezerwacja magazynowa',
                'verbose_name_plural': 'rezerwacje magazynowe',
            },
        ),
    ]
